services:
  redis-dev:
    container_name: redis-dev
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - codeigniter-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis-prod:
    container_name: redis-prod
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    networks:
      - codeigniter-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
      args:
        - CI_ENVIRONMENT=${CI_ENVIRONMENT:-development}
    environment:
      - CI_ENVIRONMENT=${CI_ENVIRONMENT:-development}
      - APP_ENV=${APP_ENV:-dev}
      - REDIS_HOST=redis-${APP_ENV}
    healthcheck:
      test: [ "CMD", "test", "-f", "/var/www/vendor/autoload.php" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./codeigniter:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - redis-${APP_ENV:-dev}
    networks:
      - codeigniter-network

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./codeigniter:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - "85:80"
      - "448:443"
    depends_on:
      - php-fpm
    networks:
      - codeigniter-network

  console-monitor:
    container_name: console-monitor
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile.cli
    environment:
      - CI_ENVIRONMENT=${CI_ENVIRONMENT:-development}
      - APP_ENV=${APP_ENV:-dev}
      - REDIS_HOST=redis-${APP_ENV}
    volumes:
      - ./codeigniter:/var/www
    command: [ "php", "spark", "monitor:start" ]
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - codeigniter-network

networks:
  codeigniter-network:
    driver: bridge